### ISSUE TITLE
invalid mode 'r+' (only r, w, b allowed)

### ISSUE THREAD

**Issue by WhyNotHugo** [lebedov/ripdb#3]
I've been trying to use ripdb (btw: thanks for doing this great merge of rpdb and ipdb!), but it's been crashing immediately upon connection.

This is how I'm using it:

```python
import ripdb
ripdb.set_trace(addr="0.0.0.0")
```

I'm passing and `addr` because this is inside a docker container.

This is the error output:

```
django_1    | Traceback (most recent call last):
django_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
django_1    |     response = get_response(request)
django_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
django_1    |     response = self.process_exception_by_middleware(e, request)
django_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
django_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1    |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
django_1    |     return self.dispatch(request, *args, **kwargs)
django_1    |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
django_1    |     return bound_func(*args, **kwargs)
django_1    |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
django_1    |     return view_func(*args, **kwargs)
django_1    |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
django_1    |     return func.__get__(self, type(self))(*args2, **kwargs2)
django_1    |   File "/app/idf/core/views/order.py", line 138, in dispatch
django_1    |     return super().dispatch(*args, **kwargs)
django_1    |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
django_1    |     return handler(request, *args, **kwargs)
django_1    |   File "/app/idf/core/views/order.py", line 142, in post
django_1    |     ripdb.set_trace(addr="0.0.0.0")
django_1    |   File "/usr/local/lib/python3.6/site-packages/ripdb/__init__.py", line 127, in set_trace
django_1    |     debugger = Rpdb(addr=addr, port=port)
django_1    |   File "/usr/local/lib/python3.6/site-packages/ripdb/__init__.py", line 57, in __init__
django_1    |     handle = connect_to_pty(clientsocket.makefile('r+', 0))
django_1    |   File "/usr/local/lib/python3.6/socket.py", line 227, in makefile
django_1    |     raise ValueError("invalid mode %r (only r, w, b allowed)" % (mode,))
django_1    | ValueError: invalid mode 'r+' (only r, w, b allowed)
```

FWIW, it looks like the offending call is wrong as per the [method docs](https://docs.python.org/3/library/socket.html#socket.socket.makefile):

>  These arguments are interpreted the same way as by the built-in open() function, except the only supported mode values are 'r' (default), 'w' and 'b'.

**Comment by lebedov** [comment]
Might require some further work, but I think I managed to get it working in Python 3.4. Give the latest revision a try.

**Comment by WhyNotHugo** [comment]
The latest from `master` worked (I don't think it's released yet, right?).

I have noticed that disconnecting from the debugger will just leave it there frozen (and I can't connect back!). I've to remember to `c` or `q` before disconnecting. But that looks like a separate issue though.

Thanks, that was really fast!

**Comment by lebedov** [comment]
Great - feel free to file a separate ticket for the freeze after disconnect issue.
